---
# handlers for notifications

- name: restart lightdm
  service: name=lightdm state=restarted

- name: reload gpgagent
  shell: echo RELOADAGENT | gpg-connect-agent
  become: yes
  become_user: "{{ username }}"
