---
- name: install docs packages
  pacman: name={{ item }} state=latest
  with_items:
  - adobe-source-sans-pro-fonts
  - ttf-liberation
  - ttf-linux-libertine
  - evince
  - pygtk
  - gnumeric
  when: ansible_os_family == "Archlinux"

## pyspread (AUR)

- name: check if pyspread already installed
  shell: pacman -Q pyspread 2>&1 | grep -v 'not found' || echo "no"
  register: pyspread_installed

- name: install pyspread packages from AUR
  shell: yaourt -S --noconfirm {{ item }}
  become: yes
  become_user: "{{ username }}"
  with_items:
  - python2-jedi
  - python2-xlrd
  - python2-gnupg
  - pyspread
  when: ansible_os_family == "Archlinux" and pyspread_installed.stdout == "no"
