---
- name: install emacs dependencies
  pacman: name={{ item }} state=latest
  with_items:
  - aspell
  - aspell-en
  when: ansible_os_family == "Archlinux"

- name: install emacs
  pacman: name=emacs state=latest
  when: ansible_os_family == "Archlinux" and gui == true

- name: install emacs (no gui)
  pacman: name=emacs-nox state=latest
  when: ansible_os_family == "Archlinux" and not gui == true

## emacs prelude

- name: check for prelude installation
  stat: path="{{ emacs.dir }}/prelude-modules.el"
  register: prelude_stat

- name: install emacs prelude
  shell: curl -L {{ emacs.prelude.installer }} || \
         PRELUDE_INSTALL_DIR="{{ emacs.dir }}" sh
  become: yes
  become_user: "{{ username }}"
  when: not prelude_stat.stat.exists

- name: update emacs prelude
  shell: git pull origin master
  args:
    chdir: "{{ emacs.dir }}"
  become: yes
  become_user: "{{ username }}"
  when: prelude_stat.stat.exists

- name: write out personal prelude emacs config files
  copy: src=dotemacs.d/personal/ dest="{{ emacs.dir }}/personal"
        owner={{ username }} group={{ username }}

- name: assure {{ username }} owns emacs.d directory
  file: path={{ home }}/.emacs.d recurse=true
        owner={{ username }} group={{ username }}

## systemd setup

- name: assure user systemd directory exists, owned by {{ username }}
  file: path={{ home }}/.config/systemd/user state=directory recurse=true
        owner={{ username }} group={{ username }}

- name: setup systemd config for emacs daemon
  copy: src=dotconfig/systemd/user/emacs.service
        dest={{ home }}/.config/systemd/user/emacs.service
        owner={{ username }} group={{ username }}
  notify: restart emacs service
