---
- name: install gui packages
  pacman: name={{ item }} state=latest
  with_items:
  - xf86-video-intel
  - mesa-libgl
  - xorg-server
  - xf86-input-synaptics
  - xorg-xrandr
  - lightdm
  - lightdm-gtk-greeter
  - xmonad
  - xmonad-contrib
  - rxvt-unicode
  - adobe-source-code-pro-fonts

## lightdm

- name: use lightdm-gtk-greeter
  lineinfile: dest=/etc/lightdm/lightdm.conf
              regexp=^\#?greeter-session=.*
              line=greeter-session=lightdm-gtk-greeter
  notify:
  - restart lightdm

- name: enable lightdm at startup and start
  service: name=lightdm enabled=yes state=started

## xmonad

- name: assure {{ username }} owns xmonad directory
  file: path={{ home }}/.xmonad state=directory
        owner={{ username }} group={{ username }} mode=0750
- name: configure xmonad
  template: src=dotxmonad/xmonad.hs.j2 dest={{ home }}/.xmonad/xmonad.hs
            owner={{ username }} group={{ username }} mode=0640

## urxvt

- name: configure urxvt
  template: src=dotXresources.j2 dest={{ home }}/.Xresources
            owner={{ username }} group={{ username }} mode=0640

