---
username: cstedman
home: "/home/{{ username }}"

# git settings
git:
  user:
    name: Carlton Stedman
    email: carlton.stedman@gmail.com
    signingkey: 4A971E66
  ssh:
    key: "{{ ssh.keydir }}/github-rsa"

# gpg settings
gpg:
  pinentry: pinentry-curses
  ttl: 3600

# enable gui (xorg)
gui: true

urxvt:
  background: rgba:1000/1000/1000/dddd
  depth: 32
  letterSpace: -1
  scrollBar: false

# rbenv settings
rbenv:
  dir: "{{ home }}/.rbenv"
  repo: https://github.com/sstephenson/rbenv
  plugins:
  - repo: https://github.com/sstephenson/ruby-build
    name: ruby-build
  - repo: https://github.com/sstephenson/rbenv-default-gems
    name: rbenv-default-gems
  gems:
  - name: bundler
    version: = 1.10.5
  - name: rake
  - name: pry
  - name: pry-coolline
  - name: pry-doc
  - name: pry-stack_explorer
  # first ruby listed is set as global default
  rubies:
  - 2.1.6

# ssh settings
ssh:
  keydir: "{{ home }}/.ssh/keys"

xft:
  antialias: true
  dpi: 96

xmonad:
  terminal: urxvt

# other xresources configs
xr:
  colors:
    background: rgb:10/10/10
    foreground: rgb:D3/D3/D3
    color0:     rgb:10/10/10
    color1:     rgb:CD/5C/5C
    color2:     rgb:2E/8B/57
    color3:     rgb:F0/E6/8C
    color4:     rgb:B0/C4/DE
    color5:     rgb:BA/55/D3
    color6:     rgb:46/82/B4
    color7:     rgb:D3/D3/D3
    color8:     rgb:4D/4D/4D
    color9:     rgb:FF/6A/6A
    color10:    rgb:8F/BC/8F
    color11:    rgb:FF/FA/CD
    color12:    rgb:1E/90/FF
    color13:    rgb:DB/70/93
    color14:    rgb:5F/9E/A0
    color15:    rgb:FF/FF/FF
  font: xft:Source Code Pro:size=11

# zsh settings
zsh:
  dir: "{{ home }}/.zsh"
  theme: miloshadzic
  plugins: gpg-agent
  sources:
  - aliases.sh
  - functions.sh
  - nocaps.sh
  - rbenv.sh

